spring:
  application:
    name: Taller3-AYGO
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:uber}?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:secret}
  sql:
    init:
      platform: mysql
      mode: always
